BEGIN;

ALTER TABLE course
    ADD COLUMN IF NOT EXISTS prerequisite_notes text,
    ADD COLUMN IF NOT EXISTS prerequisite_source text,
    ADD COLUMN IF NOT EXISTS prerequisite_source_type varchar(255);

WITH researched (code, notes, source, source_type) AS (
    VALUES
        ('CS 46A', 'Qualify through math placement M-I, M-II, or M-III, or pass MATH 1 at C- or higher. Eligible majors: CS, Applied/Computational Math, Software Engineering, Forensic Science: Digital Evidence, or Undeclared. Instructor permission is an alternative.', 'https://www.sjsu.edu/cs/docs/syllabi/fall26/CS46A_Syllabus_Sec02_Saeedeh.pdf', 'SJSU_SYLLABUS'),
        ('MATH 30', 'MATH 19, or both MATH 18A and 18B: B or higher without a workshop; C- or higher with concurrent MATH 30W. PPA placement is another route. Repeat students need MATH 30W.', 'https://www.sjsu.edu/math/calculus/index.php', 'SJSU_DEPARTMENT'),
        ('MATH 42', 'Meet MATH 30 eligibility through precalculus coursework or PPA placement; completing MATH 30 itself is not required. MATH 42W is required for the lower-grade entry route and for repeats.', 'https://www.sjsu.edu/math/calculus/index.php', 'SJSU_DEPARTMENT'),
        ('ENGL 1A', 'Complete the Reflection on College Writing placement activity before enrollment.', 'https://sjsu.edu/english/docs/syllabi/2026-spring/Criez_ENGL_1A_19_SP26.pdf', 'SJSU_SYLLABUS'),
        ('CS 46B', 'Pass CS 46A or CS 46AX at C- or higher; CS 46AW is additionally required when the introductory course was not taught in Java. Math route: placement M-I/M-II plus PPA >= 70, or MATH 19 at C- or higher, or both MATH 18A and MATH 18B at C- or higher. Eligible majors: CS, Data Science, CS and Linguistics, Statistics, Applied/Computational Math, Software Engineering, or Forensic Science: Digital Evidence.', 'https://www.sjsu.edu/cs/docs/syllabi/fall26/CS46B_Introduction_to_Data_Structures_Fall_2026_section_1_Luo.pdf', 'SJSU_SYLLABUS'),
        ('MATH 31', 'MATH 30 at B or higher, or AP Calculus AB >= 4. MATH 30 at C- or higher, or AP AB >= 3, requires concurrent MATH 31W. Repeats require the workshop.', 'https://www.sjsu.edu/math/calculus/index.php', 'SJSU_DEPARTMENT'),
        ('CS 47', 'CS 42/MATH 42 plus CS 46B; the syllabus specifies C- or higher. Eligible majors: CS, Data Science, or Forensic Science: Digital Evidence.', 'https://www.sjsu.edu/cs/docs/syllabi/fall26/Introduction_to_Computer_Systems_CS_47_Fall_2026_Paravastu.pdf', 'SJSU_SYLLABUS'),
        ('CS 146', 'Complete MATH 30, MATH 42, and CS 46B at C- or higher. CS 46B must have been taught in Java; otherwise also complete CS 49J or provide accepted evidence of equivalent Java preparation.', 'https://www.sjsu.edu/cs/docs/syllabi/fall26/Syllabus%20CS%20146-01%20Fall%202026%20Navrati%20Saxena.pdf', 'SJSU_SYLLABUS'),
        ('PHYS 50', 'Provisional: writing placement I/II/III, completed GE A2 at C- or higher, or ENGL 1AF with CR; plus AP Calculus >= 3 or MATH 30/30P/30PL/30X at C- or higher. Science or Engineering major required. Register for the lab. The listing also permits a postbaccalaureate writing route; confirm with SJSU.', 'https://www.coursicle.com/sjsu/courses/PHYS/50/', 'SECONDARY_PENDING_CATALOG'),
        ('GEOL 1', 'Provisional: the secondary course listing specifies no prerequisite. Lecture, lab, and field trips are included. Absence of a listed prerequisite has not been confirmed against the 2026-2027 SJSU catalog.', 'https://www.coursicle.com/sjsu/courses/GEOL/1/', 'SECONDARY_PENDING_CATALOG'),
        ('GEOL 7', 'Provisional: the secondary course listing specifies no prerequisite. Lecture and lab are included; field trips may be required. Absence of a listed prerequisite has not been confirmed against the 2026-2027 SJSU catalog.', 'https://www.coursicle.com/sjsu/courses/GEOL/7/', 'SECONDARY_PENDING_CATALOG'),
        ('CS 147', 'Complete CS 47, CMPE 102, or an accepted equivalent at C- or higher.', 'https://www.sjsu.edu/cs/docs/syllabi/fall26/CS147_Computer-Arch-Syllabus-Rao.pdf', 'SJSU_SYLLABUS'),
        ('CS 151', 'Complete MATH 42 and CS 46B at C- or higher. If CS 46B was not taught in Java, also pass CS 48 or CS 49J at C- or higher. Eligible majors: CS, Applied/Computational Math, Software Engineering, or Data Science; instructor permission is an alternative.', 'https://www.sjsu.edu/cs/docs/syllabi/fall26/Object_Oriented_Design_CS_151_Fall_2026_Kim.pdf', 'SJSU_SYLLABUS'),
        ('MATH 39', 'Provisional: MATH 31 at C- or higher, or instructor permission. The enrollment listing also accepts MATH 31X, AP Calculus BC >= 3, or qualifying transfer work (TR32/T32B). Confirm current alternatives with SJSU.', 'https://www.coursicle.com/sjsu/courses/MATH/39/', 'SECONDARY_PENDING_CATALOG'),
        ('CS 149', 'Complete CS 146 and either CS 47 or CMPE 102, all at C- or higher. Eligible majors: CS, Applied/Computational Math, Forensic Science: Digital Evidence, or Software Engineering; instructor permission is an alternative.', 'https://www.sjsu.edu/cs/docs/syllabi/fall26/Operating_Systems_CS_149_Fall_2026_Andreopoulos.pdf', 'SJSU_SYLLABUS'),
        ('BIOL 30', 'Provisional: writing placement W-I/W-II, ENGL 1AF with CR, or ENGL 1A at C- or higher; plus math placement M-I/M-II or a completed GE Area 2 course. Restricted to listed majors, including CS, Biology, Biomedical Engineering, Biochemistry, Environmental Studies, Forensic Science (Biology/Chemistry), Nutritional Science, Meteorology, Kinesiology, and Communicative Disorders. The same page''s enrollment section also lists writing category III; this conflict needs SJSU confirmation.', 'https://www.coursicle.com/sjsu/courses/BIOL/30/', 'SECONDARY_PENDING_CATALOG'),
        ('CS 152', 'Pass CS 151 or CMPE 135 at C- or higher. Eligible majors: CS or Software Engineering; instructor permission is an alternative.', 'https://www.sjsu.edu/cs/docs/syllabi/fall26/Austin_CS_152_Fall_2026.pdf', 'SJSU_SYLLABUS'),
        ('PHIL 134', 'Finish Core GE and reach upper-division standing. Taking or completing 100W is recommended, not mandatory in this source. The supplied roadmap specifies at least 60 completed units for upper-division GE.', 'https://ischool.sjsu.edu/bsisda-required-courses', 'SJSU_DEPARTMENT'),
        ('CS 100W', 'Undergraduate route: GE A3 or an equivalent second composition course at C- or higher, completed Core GE, and upper-division standing. Graduate/postbaccalaureate standing is another route. Eligible majors: CS, Data Science, CS and Linguistics, or Mathematics. The Fall 2026 syllabus retains the older A3 area label.', 'https://www.sjsu.edu/cs/docs/syllabi/fall26/CS_100W_Sec01-Fall_2026-Cheilek.pdf', 'SJSU_SYLLABUS'),
        ('MATH 32', 'MATH 31 at B or higher, or AP Calculus BC >= 4. MATH 31 at C- or higher, or AP BC >= 3, requires concurrent MATH 32W. Repeats require the workshop.', 'https://www.sjsu.edu/math/calculus/index.php', 'SJSU_DEPARTMENT'),
        ('MATH 142', 'Provisional: MATH 31 and MATH 42, each at C- or higher, or instructor permission. The enrollment listing also accepts MATH 31X/42X alternatives. Eligible programs: Mathematics major/minor, CS, BS Data Science, or Software Engineering.', 'https://www.coursicle.com/sjsu/courses/MATH/142/', 'SECONDARY_PENDING_CATALOG'),
        ('MATH 161A', 'Provisional: MATH 31 at C- or higher, or instructor permission. The enrollment listing additionally mentions MATH 31X and transfer groups TR32/T32B; confirm these routes with SJSU.', 'https://www.coursicle.com/sjsu/courses/MATH/161A/', 'SECONDARY_PENDING_CATALOG'),
        ('CS 157A', 'Pass CS 146 at C- or higher. The syllabus course description permits CS, Applied/Computational Math, or Software Engineering majors, or instructor permission. Its introductory prerequisite box omits Software Engineering; confirm that major restriction if relevant.', 'https://www.sjsu.edu/cs/docs/syllabi/fall26/CS157A-01%20Fall%202026-%20Syllabus_Wu.pdf', 'SJSU_SYLLABUS'),
        ('CS 160', 'Complete CS 146 and CS 151 at C- or higher, plus CS 100W at C or higher. Eligible majors: CS, Forensic Science: Digital Evidence, or Software Engineering. The course description includes an instructor-permission alternative.', 'https://www.sjsu.edu/cs/docs/syllabi/fall26/DominicAbucejo_FA2026_CS_160_Section_5.pdf', 'SJSU_SYLLABUS'),
        ('CS 166', 'Complete CS 146 plus one of CS 47, CMPE 102, or CMPE 120, all at C- or higher. Eligible majors: CS, Applied/Computational Math, or Software Engineering; instructor permission is an alternative.', 'https://www.sjsu.edu/cs/docs/syllabi/fall26/2026%20Fall%20-%20CS166%20-%20Section%201%20-Fabio%20Di%20Troia.pdf', 'SJSU_SYLLABUS'),
        ('CS 154', 'Complete CS 46B and either MATH 42 or MATH 42X, each at C- or higher. Eligible majors: CS or Applied/Computational Mathematics; instructor permission is an alternative.', 'https://www.sjsu.edu/cs/docs/syllabi/fall26/Formal_Languages_and_Computability_CS_154_Fall_2026_Chen.pdf', 'SJSU_SYLLABUS')
)
UPDATE course AS existing
SET prerequisite_notes = researched.notes,
    prerequisite_source = researched.source,
    prerequisite_source_type = researched.source_type
FROM researched
WHERE existing.code = researched.code
    AND (existing.prerequisite_notes, existing.prerequisite_source, existing.prerequisite_source_type)
        IS DISTINCT FROM (researched.notes, researched.source, researched.source_type)
RETURNING existing.code, existing.prerequisite_source_type;

COMMIT;
