spring.application.name=course_planner
spring.datasource.url=jdbc:postgresql://localhost:5432/courseplanner
spring.datasource.username=Lin
spring.datasource.password=Lintrofish

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true